#!/usr/bin/python3

import argparse

def reverse_bits(byte):
    res = 0

    for i in range(8):
        res <<= 1
        res |= byte & 1
        byte >>= 1

    return res

def reverse_bits7(byte):
    res = 0

    for i in range(7):
        res <<= 1
        res |= byte & 1
        byte >>= 1

    res |= (byte & 1) << 7

    return res

parser = argparse.ArgumentParser(
                    prog='assemblify',
                    description='Convert a binary file to an assembly file')

parser.add_argument('src_file', help='Source binary file')
parser.add_argument('out_file', help='Output assembly file')
parser.add_argument('--section', type=str, help='Assembly file defines itself in this section')
parser.add_argument('--section-flags', type=str, help='Section flags to use')
parser.add_argument('--symbol', type=str, help='Mark data with a global symbol')
parser.add_argument('--bytes-per-line', type=int, default=16, help='Number of bytes to issue per assembly line')
parser.add_argument('--align', type=int, default=16, help="Ask for the symbol's address to cleanly divide by a certain value")
parser.add_argument('--reverse', action="store_true", default=False, help="Reverses each byte (LSB becomes MSB)")
parser.add_argument('--reverse7', action="store_true", default=False, help="Reverses the lower 7 bits of each byte (LSB becomes bit 6)")

args = parser.parse_args()

with open(args.src_file, "rb") as src_file, open(args.out_file, 'w') as out_file:
    if args.section is not None:
        print(f".section {args.section}", end="", file=out_file)
        if args.section_flags is not None:
            print(f', "{args.section_flags}"', file=out_file)
        else:
            print(file=out_file)

    if args.align is not None:
        print(f".balign {args.align}", file=out_file)

    if args.symbol is not None:
        print(f".global {args.symbol}", file=out_file)
        print(f"{args.symbol}:", file=out_file)

    line_index = 0
    while( b := src_file.read1(1) ):
        b = ord(b)
        if args.reverse:
            b = reverse_bits(b)

        if args.reverse7:
            b = reverse_bits7(b)

        if line_index == 0:
            print(f"    .dc.b {hex(b)}", end="", file=out_file)
        else:
            print(f", {hex(b)}", end="", file=out_file)

        line_index = line_index+1
        if line_index == args.bytes_per_line:
            print(file=out_file)
            line_index = 0

    if line_index != 0:
        print(file=out_file)
